/* 测试一用 */
export const JS_MSG_HANDLE = 'JS_MSG_HANDLE'
/* 程序本地数据库初始化 */
export const QUERY_INITIALIZETE_COMPLETED_REQUEST = 'QUERY_INITIALIZETE_COMPLETED_REQUEST'
export const WIMDOW_INITIALIZE_FONT_DB_REQUEST = 'WIMDOW_INITIALIZE_FONT_DB_REQUEST'
/* 页面数据初始化 */
export const INITIALIZATION_DATA = 'INITIALIZATION_DATA'
export const INITIALIZATION_LOADING_DATA = 'INITIALIZATION_LOADING_DATA'
export const INITIALIZATION_EVENTS_CALLBACK = 'INITIALIZATION_EVENTS_CALLBACK'
export const EVENTS_INITIALIZATION_DATA = 'EVENTS_INITIALIZATION_DATA'
export const INITIALIZATION_ERROR_DATA = 'INITIALIZATION_ERROR_DATA'
export const INITIALIZATION_OLD_DATA = 'INITIALIZATION_OLD_DATA'
/* 路由初始化 */
export const GET_INIT_ROUTE = 'GET_INIT_ROUTE'
/* 页面弹出层定义 */
export const TRIGGER_DIALOG_INFO = 'TRIGGER_DIALOG_INFO'
export const TRIGGER_MINMIZE_INFO = 'TRIGGER_MINMIZE_INFO'
export const SMART_MENU_INFO = 'SMART_MENU_INFO'

export const RECEIVE_COLLECT_GO_POSTS = 'RECEIVE_COLLECT_GO_POSTS'
export const RECEIVE_SINGLE_LIST_GO_POSTS = 'RECEIVE_SINGLE_LIST_GO_POSTS'
export const RECEIVE_SINGLE_ITEM_GO_POSTS = 'RECEIVE_SINGLE_ITEM_GO_POSTS'
export const RECEIVE_SEARCH_GO_POSTS = 'RECEIVE_SEARCH_GO_POSTS'
export const RECEIVE_ADD_SINGLE_FONT_GO_POSTS = 'RECEIVE_ADD_SINGLE_FONT_GO_POSTS'
export const RECEIVE_LOGIN_USER_SUBMIT_LIANTY_POSTS = 'RECEIVE_LOGIN_USER_SUBMIT_LIANTY_POSTS'
export const RECEIVE_LOGIN_THIRD_USER_SUBMIT_LIANTY_POSTS = 'RECEIVE_LOGIN_THIRD_USER_SUBMIT_LIANTY_POSTS'
export const RECEIVE_GET_FONTS_BY_FONT_ID = 'RECEIVE_GET_FONTS_BY_FONT_ID'
export const RECEVIE_GET_PREVIEW_IMAGE = 'RECEVIE_GET_PREVIEW_IMAGE'
export const RECEVIE_GET_FONTS_BY_FONT_ITEM_ID = 'RECEVIE_GET_FONTS_BY_FONT_ITEM_ID'
export const RECEIVE_ASYNC_GET_FONT_REQUEST = 'RECEIVE_ASYNC_GET_FONT_REQUEST'
export const RECEIVE_ASYNC_DRAG_DROP_REQUEST = 'RECEIVE_ASYNC_DRAG_DROP_REQUEST'

export const RECEIVE_ASYNC_GET_FILE_REQUEST = 'RECEIVE_ASYNC_GET_FILE_REQUEST'
export const RECEIVE_ASYNC_GET_SCAN_DOCS_INIT_REQUEST = 'RECEIVE_ASYNC_GET_SCAN_DOCS_INIT_REQUEST'
export const RECEIVE_ASYNC_GET_FILE_REQUEST_ALWAYS = 'RECEIVE_ASYNC_GET_FILE_REQUEST_ALWAYS'
export const RECEIVE_ASYNC_SET_SCAN_DOCS_PATH_REQUEST = 'RECEIVE_ASYNC_SET_SCAN_DOCS_PATH_REQUEST'
export const RECEIVE_ASYNC_ADD_SCAN_DOCS_PATH_REQUEST = 'RECEIVE_ASYNC_ADD_SCAN_DOCS_PATH_REQUEST'
export const RECEIVE_SET_SCAN_DOCS_FILTER_REQUEST = 'RECEIVE_SET_SCAN_DOCS_FILTER_REQUEST'
export const RECEIVE_ASYNC_GET_SCAN_DOCS_REQUEST = 'RECEIVE_ASYNC_GET_SCAN_DOCS_REQUEST'
export const RECEIVE_ASYNC_PAUSE_SCAN_DOCS_REQUEST = 'RECEIVE_ASYNC_PAUSE_SCAN_DOCS_REQUEST'
export const RECEIVE_ASYNC_REFRESH_SCAN_DOCS_REQUEST = 'RECEIVE_ASYNC_REFRESH_SCAN_DOCS_REQUEST'
export const RECEVIE_ASYNC_DELECTE_SCAN_DOCS_REQUEST = 'RECEVIE_ASYNC_DELECTE_SCAN_DOCS_REQUEST'
export const RECEIVE_ASYNC_STOP_SCAN_DOCS_REQUEST = 'RECEIVE_ASYNC_STOP_SCAN_DOCS_REQUEST'
export const RECEVIE_ASYNC_GET_DOCS_INFO_REQUEST = 'RECEVIE_ASYNC_GET_DOCS_INFO_REQUEST'
export const RECEVIE_ASYNC_SET_SCAN_DOCS_LOOP_SCAN_REQUEST = 'RECEVIE_ASYNC_SET_SCAN_DOCS_LOOP_SCAN_REQUEST'

export const RECEIVE_ASYNC_GET_ADD_FRIEND_REQUEST = 'RECEIVE_ASYNC_GET_ADD_FRIEND_REQUEST'
export const RECEVIE_ASYNC_SEARCH_FILE_BY_TEXT_REQUEST = 'RECEVIE_ASYNC_SEARCH_FILE_BY_TEXT_REQUEST'
export const RECEVIE_ASYNC_PASTE_DATA = 'RECEVIE_ASYNC_PASTE_DATA'

export const WINDOW_LOGIN_USER_REQUEST = 'WINDOW_LOGIN_USER_REQUEST'
export const WINDOW_GET_FONT_REQUEST = 'WINDOW_GET_FONT_REQUEST'
export const WINDOW_COLLECTED_FONT_REQUEST = 'WINDOW_COLLECTED_FONT_REQUEST'
export const WIMDOW_UNINSTALL_FONT_DEL = 'WIMDOW_UNINSTALL_FONT_DEL'
export const WIMDOW_INSTALL_FONT_ADD = 'WIMDOW_INSTALL_FONT_ADD'
export const WIMDOW_UN_OR_COLLECT_FONTS = 'WIMDOW_UN_OR_COLLECT_FONTS'
export const WINDOW_GET_DOWNLOAD_LIST = 'WINDOW_GET_DOWNLOAD_LIST'
export const ADD_GET_DOWNLOAD_BEGING = 'ADD_GET_DOWNLOAD_BEGING'
export const WINDOW_GET_DOWNLOAD_BEGING = 'WINDOW_GET_DOWNLOAD_BEGING'
export const WINDOW_PS_FILE_DETECT_REQUEST = 'WINDOW_PS_FILE_DETECT_REQUEST'
export const WINDOW_OPEN_FILE_REQUEST = 'WINDOW_OPEN_FILE_REQUEST'
export const WINDOW_HISTORY_DETECT_REQUEST = 'WINDOW_HISTORY_DETECT_REQUEST'

export const EVENTS_GET_PREVIEW_IMAGE = 'EVENTS_GET_PREVIEW_IMAGE'
export const EVENTS_GET_DOWNLOAD_LIST = 'EVENTS_GET_DOWNLOAD_LIST'
export const EVENTS_ONE_KEY_WARPER_REQUEST = 'EVENTS_ONE_KEY_WARPER_REQUEST'
export const EVENTS_KEY_PADDED = 'EVENTS_KEY_PADDED'
export const EVENTS_CLEAR_DETECT = 'EVENTS_CLEAR_DETECT'
export const EVENTS_OPEN_FILE_REQUEST = 'EVENTS_OPEN_FILE_REQUEST'
export const EVENTS_IS_SCAN_FINISHED_REQUEST = 'EVENTS_IS_SCAN_FINISHED_REQUEST'
export const EVENTS_GET_SORT_FILTER_DATA = 'EVENTS_GET_SORT_FILTER_DATA'
export const EVENTS_ATTRIBUTES_DATA = 'EVENTS_ATTRIBUTES_DATA'
export const EVENTS_UN_OR_CHECK_ITEM = 'EVENTS_UN_OR_CHECK_ITEM'
export const EVENTS_UN_OR_ALLCHECK_ITEM = 'EVENTS_UN_OR_ALLCHECK_ITEM'
export const EVENTS_UNCHECK = 'EVENTS_UNCHECK'
export const EVENTS_CHECK = 'EVENTS_CHECK'

export const INIT_GET_CONFIG_INFO = 'INIT_GET_CONFIG_INFO'
export const INIT_SET_CONFIG_INFO = 'INIT_SET_CONFIG_INFO'
export const INIT_SET_CONFIG_DEFAULT = 'INIT_SET_CONFIG_DEFAULT'

export const FONT_ATTRIBUTES_DATA = 'FONT_ATTRIBUTES_DATA'
export const FONT_UN_OR_CHECK_ITEM = 'FONT_UN_OR_CHECK_ITEM'
export const FONT_UN_OR_ALLCHECK_ITEM = 'FONT_UN_OR_ALLCHECK_ITEM'
export const FONT_UN_AllCHECK_ITEM = 'FONT_UN_AllCHECK_ITEM'

/* 登录有关模块 */
export const DO_NOT_LOGIN = 'DO_NOT_LOGIN'
export const GET_HISTORY_USER_DATA = 'GET_HISTORY_USER_DATA'
export const LOGIN_USER_SUBMIT = 'LOGIN_USER_SUBMIT'
export const LOGIN_THIRD_USER_SUBMIT = 'LOGIN_THIRD_USER_SUBMIT'
export const SET_LOGIN_USER_REQUEST = 'SET_LOGIN_USER_REQUEST'

export const SET_REGIST_PHONE_DATA = 'SET_REGIST_PHONE_DATA'
export const SET_REGIST_EMAIL_DATA = 'SET_REGIST_EMAIL_DATA'
export const SET_LOGIN_WNDSIZE_DATA = 'SET_LOGIN_WNDSIZE_DATA'

export const GET_FONTS_BY_FONT_ID = 'GET_FONTS_BY_FONT_ID'


/* myFonts */
export const MYFONTS_ALL_FONT_LIST_DATA = 'MYFONTS_ALL_FONT_LIST_DATA'
export const MYFONTS_INSTALLED_FONT_LIST_DATA = 'MYFONTS_INSTALLED_FONT_LIST_DATA'
export const MYFONTS_UNINSTALL_FONT_LIST_DATA = 'MYFONTS_UNINSTALL_FONT_LIST_DATA'
export const MYFONTS_COLLECTED_FONT_LIST_DATA = 'MYFONTS_COLLECTED_FONT_LIST_DATA'
export const MYFONTS_COLLECTED_FONT_LIST_DATA_YUN = 'MYFONTS_COLLECTED_FONT_LIST_DATA_YUN'
export const MYFONTS_GET_DOWNLOAD_LIST_DATA = 'MYFONTS_GET_DOWNLOAD_LIST_DATA'
export const GET_DOWNLOAD_FONT_BEGING = 'GET_DOWNLOAD_FONT_BEGING'
export const GET_DOWNLOAD_FONT_PROGRESS = 'GET_DOWNLOAD_FONT_PROGRESS'

/* misssing */
export const MISSING_ONE_KEY_WARPE = 'MISSING_ONE_KEY_WARPE'
export const MISSING_KEY_PADDED = 'MISSING_KEY_PADDED'

/* createSingleFonts */
export const SAVE_ADD_SINGLE_FONT = 'SAVE_ADD_SINGLE_FONT'
export const GET_SINGLE_FONTS_LIST_DATA = 'GET_SINGLE_FONTS_LIST_DATA'
export const GET_SINGLE_FONTS_ITEM_DATA = 'GET_SINGLE_FONTS_ITEM_DATA'

/* fontBtn */
export const UNINSTALL_FONT_DEL = 'UNINSTALL_FONT_DEL'
export const UN_OR_COLLECT_FONTS = 'UN_OR_COLLECT_FONTS'

/* search */
export const SEARCH_COLLECTED_FONT_LIST = 'SEARCH_COLLECTED_FONT_LIST'

/* tag */
export const SELECT_TAG_SAVE = 'SELECT_TAG_SAVE'

/* message */
export const MESSAGE_DEFAULT = 'MESSAGE_DEFAULT'
export const MESSAGE_DOWNLOAD_NUMBER = 'MESSAGE_DOWNLOAD_NUMBER'
export const MESSAGE_INSTALL_NUMBER = 'MESSAGE_INSTALL_NUMBER'
export const MESSAGE_NOTICE = 'MESSAGE_NOTICE'
export const MESSAGE_ADD_SCAN = 'MESSAGE_ADD_SCAN'
export const MESSAGE_MODE_CHANGE = 'MESSAGE_MODE_CHANGE'
export const MESSAGE_FILE_INFO = 'MESSAGE_FILE_INFO'
export const MESSAGE_SEARCH_FILE = 'MESSAGE_SEARCH_FILE'

export const GET_NO_DEAL_MESSAGE_LIST = 'GET_NO_DEAL_MESSAGE_LIST'
export const DO_DEAL = 'DO_DEAL'
export const GET_PC_NOTICE_MESSAGE = 'GET_PC_NOTICE_MESSAGE'

/* 确认框标识符 */
export const SET_SCAN_PATH_DEL = 'SET_SCAN_PATH_DEL'

/* chat */
export const GET_YUN_CHAT_ACCID = 'GET_YUN_CHAT_ACCID'
export const FIND_YUN_FRIEND = 'FIND_YUN_FRIEND'
/*视图*/
export const GET_SHITU_ID = 'GET_SHITU_ID'
export const GET_SEARCH_FONT_RESULT = 'GET_SEARCH_FONT_RESULT'
export const GET_SHITU_IMG = 'GET_SHITU_IMG'
export const GET_SHITU_IMG_FAIL = 'GET_SHITU_IMG_FAIL'
export const GET_SEARCH_IMG_RESULT = 'GET_SEARCH_IMG_RESULT'
export const OPEN_IMG_DRAG = 'OPEN_IMG_DRAG'
export const GET_SCANNING_RESULT = 'GET_SCANNING_RESULT'
export const GET_SHITU_INPUTID='GET_SHITU_INPUTID'
export const GET_SHITU_SERIVE = 'GET_SHITU_SERIVE'